from __future__ import annotations

from typing import Dict, Set

# Slang / shorthand normalization (token-level)
NORM_DICT: Dict[str, str] = {
	# Negation variants -> tidak
	"gk": "tidak",
	"gak": "tidak",
	"ga": "tidak",
	"nggak": "tidak",
	"enggak": "tidak",
	"kagak": "tidak",
	"tak": "tidak",
	"yg": "yang",
	"yyg": "yang",
	"aja": "saja",
	"bgt": "banget",
	"org": "orang",
	"udh": "sudah",
	"udah": "sudah",
	"sdh": "sudah",
	"klo": "kalau",
	"kalo": "kalau",
	"dgn": "dengan",
	"dg": "dengan",
	"blm": "belum",
	"tp": "tapi",
	"tpi": "tapi",
	"gmn": "gimana",
	"bgs": "bagus",
	"mntp": "mantap",
	"mntop": "mantap",
	"anjg": "anjing",
	"anjink": "anjing",
	"cm": "cuma",
	"cuma": "cuma",
	"krn": "karena",
	"kmrn": "kemarin",
	"sm": "sama",
	"sma": "sama",
	"sy": "saya",
	"sya": "saya",
	"dlm": "dalam",
	"dlu": "dulu",
	"ntr": "nanti",
	"nnti": "nanti",
	"skrg": "sekarang",
	"skg": "sekarang",
	"thn": "tahun",
	"bln": "bulan",
	"hr": "hari",
	"mlm": "malam",
	"pagi2": "pagi",
	"siang2": "siang",
	"sore2": "sore",
	"mlm2": "malam",
	"kmn": "kemana",
	"dmn": "dimana",
	"dmn2": "dimana",
	"bbrp": "beberapa",
	"brp": "berapa",
	"gk": "tidak",
	"gak": "tidak",
	"ga": "tidak",
	"nggak": "tidak",
	"enggak": "tidak",
	"kagak": "tidak",
	"jgn": "jangan",
	"jangan": "jangan",
	"plis": "tolong",
	"pls": "tolong",
	"thx": "terima kasih",
	"ty": "terima kasih",
	"makasih": "terima kasih",
	"mksh": "terima kasih",
	"mkasih": "terima kasih",
	"trmksh": "terima kasih",
	"trmkasih": "terima kasih",
	"tq": "terima kasih",
	" tq": " terima kasih",
	"tysm": "terima kasih banyak",
	"trims": "terima kasih banyak",
	"trimakasih": "terima kasih",
	"trimakasi": "terima kasih",
	"trima kasih": "terima kasih",
	"thx bgt": "terima kasih banget",
	"thx banget": "terima kasih banget",
	"terimakasih": "terima kasih",
	"terimakasi": "terima kasih",
	"makasi": "terima kasih",
	"makasii": "terima kasih",
	"makasiii": "terima kasih",
	"makasiiii": "terima kasih",
	"makasiiiii": "terima kasih",
	"thx a lot": "terima kasih banyak",
	"thanks a lot": "terima kasih banyak",
	"thanks": "terima kasih",
	"thx": "terima kasih",
	"ty": "terima kasih",
	"thankyou": "terima kasih",
	"thank you": "terima kasih",
	"luv": "love",
	"love": "cinta",
	"plng": "paling",
	"plg": "paling",
	"smoga": "semoga",
	"moga": "semoga",
	"bsk": "besok",
	"bsok": "besok",
	"brngkt": "berangkat",
	"brangkat": "berangkat",
	"ggr": "ganggu",
	"gganggu": "ganggu",
	"gangu": "ganggu",
	"syg": "sayang",
	"syang": "sayang",
	"sayng": "sayang",
	"sayang": "sayang",
	"ak" : "aku",
	"akuu" : "aku",
	"wopyu" : "love you",
	"okesi" : "oke",
	"tervaik" : "terbaik",
	"naise" : "nice",
	"trimakasih" : "terima kasih",
	"muass" : "puas",
	"andd" : "dan",
	"kakak2" : "kakak",
	"dri" : "dari",
	"vitur" : "fitur",
	"dll" : "dan lain lain",
	"robloc" : "roblox",
	"roblok" : "roblox",
	"spinan" : "wheel spin",
	"doi" : "dia",
	"kasi" : "kasih",
	"sana" : "sono",
	"updatee" : "update",
	"u" : "you",
	"lope" : "love",
	"lov" : "love",
	"lve" : "love",
	"louv" : "love",
	"lvoe" : "love",
	"badag" : "gila",
	"pokonamah" : "pokoknya",
	"mntop" : "mantap",
	"kerenn" : "keren",
	"mbuh" : "entah",
	"skop" : "sekop",
	"ya" : "iya",
	"waa" : "wah",
	"grapic" : "grafik",
	"sii" : "sih",
	"plis" : "tolong",
	"pliss" : "tolong",
	"plisss" : "tolong",
	"gg" : "good game",
	"p2w" : "pay to win",
	"hp" : "handphone",
	"dc" : "disconnect",
	"mice" : "nice",
	"domein" : "domain",
	"naice" : "nice",
	"bugg" : "bug",
	"pke" : "pakai",
	"pake" : "pakai",
	"patah2" : "patah",
	"kapitaliss" : "kapitalis",
	"tidurr" : "tidur",
	"suzah" : "susah",
	"orng" : "orang",
	"favorit" : "favorit",
	"teman2" : "teman",
	"fitures" : "fitur",
	"bintang1" : "bintang satu",
	"omgg" : "oh my god",
	"omg" : "oh my god",
	"auraa" : "aura",
	"maah" : "mah",
	"lucuu" : "lucu",
	"gud" : "good",
	"min" : "admin",
	"lot" : "alot",
	"skli" : "sekali",
	"tho" : "toh",
	"smngat" : "semangat",
	"sharian" : "seharian",
	"teman2" : "teman",
	"adaa" : "ada",
	"gua" : "saya",
}

# Fallback stopwords if NLTK stopwords corpus isn't available
STOPWORDS_BASE: Set[str] = {
	"yang", "dan", "atau", "di", "ke", "dari", "pada", "untuk", "dengan", "karena", "bahwa",
	"itu", "ini", "saya", "aku", "kami", "kita", "kamu", "dia", "mereka",
	"ada", "jadi", "kalau", "jika", "sebagai", "agar", "supaya", "bisa", "dapat",
	"akan", "sudah", "belum", "harus", "buat", "sini", "sana", "saat", "waktu",
	"atau", "tetapi", "tapi", "namun", "meskipun", "walaupun", "sehingga", "jadi",
	"adalah", "ialah", "yaitu", "seperti", "pula", "lagi", "lagi pula", "tentang",
	"lebih", "kurang", "sangat", "sekali", "hanya", "cuma", "saja", "sungguh", "amat"
}
BLACKLIST_WORD: Set[str] = {
	"vvbhuu", "aasdad", "awdawawawdaw", "asdasdasd", "asdasd", "adadad", "adadada", "qwertyuiop", "asdfghjkl", "zxcvbnm",
	"qwerty", "asdfgh", "zxcvbn", "123456", "1234567", "12345678", "123456789", "1234567890",
	"qwe123", "qweasd", "qweasdzxc", "qazwsx", "1q2w3e", "password", "passw0rd", "admin", "user",
	"kontol", "anjing", "bajingan", "babi", "bangsat", "tai", "memek", "jembut", "brengsek",
	"goblok", "bego", "tolol", "kampang", "pantek", "perek", "pepek", "ngentot", "ngewe", "setan",
	"celeng", "monyet", "sundal", "sundel", "bejad", "brengsek", "bacot", "banci", "bajingan",
	"brengsek", "taiyem", "taiyeim", "tai yeim", "tai yem", "tai ampas", "tai ampaz", "tai kucing",
	"defe", "nyo", "sungbewoo", "vvbhuu", "titid", "awdawawawdaw", "yrhdbhehe", "hay", 
	"yeap", "yepp", "yeppp", "yess", "yesss", "woi", "woii", "woiii", "whatsapp", "wa", "watsapp",
	"avv", "se", "mommydea", "skdnalkdnsalkdsakdsandklsa", "nyuak", "jo", "yoz", "yozoya", "yojoya", "bgyozz",
	"linghe", "unosize", "ngentot", "ngewe", "setan", "josjis", "dadzz", "rpg", "vr", "edo", "yozz"
	"rawr", "natara", "fedo", "kedat", "kedut", "kiw", "intang", "noh", "cuekin", "yozoyaa", "ira", "yeapp", "deym", "omaga"
}

DEFAULT_FLAGS: Dict[str, bool] = {
	"normalize_slang": True,
	"drop_invalid_rows": True,
	"cleanup_digits": True,
	"cleanup_spam_tokens": True,
	"use_english_stopwords": False,
}

def export_preprocess_config() -> dict:
	return {
		"norm_dict": dict(NORM_DICT),
		"stopwords_base": sorted(STOPWORDS_BASE),
		"blacklist_word": sorted(BLACKLIST_WORD),
		"default_flags": dict(DEFAULT_FLAGS),
	}
